server:
  port: ${PORT:8083}
  servlet:
    session:
      timeout: 40m

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/finplanpro}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile

app:
  base-url: ${APP_BASE_URL:http://localhost:8083}

flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration
  clean-on-validation-error: false

management:
  endpoints:
    web:
      exposure:
        include: health
