CREATE TABLE tax_records (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    tax_year INT NOT NULL,
    monthly_income NUMERIC(19, 2) DEFAULT 0,
    other_annual_income NUMERIC(19, 2) DEFAULT 0,
    has_spouse BOOLEAN DEFAULT FALSE,
    children_count INT DEFAULT 0,
    parent_count INT DEFAULT 0,
    disabled_care_count INT DEFAULT 0,
    life_insurance_premium NUMERIC(19, 2) DEFAULT 0,
    health_insurance_premium NUMERIC(19, 2) DEFAULT 0,
    parent_health_insurance_premium NUMERIC(19, 2) DEFAULT 0,
    pension_insurance_premium NUMERIC(19, 2) DEFAULT 0,
    provident_fund NUMERIC(19, 2) DEFAULT 0,
    rmf NUMERIC(19, 2) DEFAULT 0,
    ssf NUMERIC(19, 2) DEFAULT 0,
    nac NUMERIC(19, 2) DEFAULT 0,
    total_income NUMERIC(19, 2) DEFAULT 0,
    total_deduction NUMERIC(19, 2) DEFAULT 0,
    net_taxable_income NUMERIC(19, 2) DEFAULT 0,
    tax_payable NUMERIC(19, 2) DEFAULT 0,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);
